### ISSUE TITLE
chat doesnt auto scroll

### ISSUE THREAD

**Issue by smelvinjones** [z3db0y/rays-nova#2] opened 2024-03-15 09:02 UTC
the chat doesnt auto scroll and when you enter the next game (like in same lobby) it stops updating until u refresh

**Comment by z3db0y** [comment] 2024-03-15 09:16
So the issue is the scrolling itself; no issues with new messages not being added? Because I have noticed the scrolling issue as well and will fix it in the near future

**Comment by smelvinjones** [comment] 2024-03-15 11:00
> and when you enter the next game (like in same lobby) it stops updating until u refresh

edit: when there are more than 34 or 35 lines in the chat (whether its killfeed or chat or whatever and doesnt matter if it is hidden/not selected) then it stops updating

**Comment by z3db0y** [comment] 2024-03-22 14:26
o shi i forgor abt this issue
will fix rq

**Comment by z3db0y** [comment] 2024-03-22 14:57
Fixed in 0b45cf9cb39a43a3f7223c4200a2739cc7999cc9

**Closed as completed by z3db0y** 2024-03-22 14:57 UTC
Labels: bug
